In [1]:
import numpy as np

In [2]:
my_list = [10,20,30,40]

In [3]:
type(my_list)

list

In [4]:
np.array(my_list)

array([10, 20, 30, 40])

In [5]:
my_numpy_array = np.array([10,20,30,40])

In [6]:
type(my_numpy_array)

numpy.ndarray

In [7]:
my_numpy_array.max()

np.int64(40)

In [8]:
my_numpy_array.min()

np.int64(10)

In [9]:
my_numpy_array.max() - my_numpy_array.min()

np.int64(30)

In [10]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [11]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.random.random(9)

array([0.67211084, 0.87982657, 0.06360572, 0.45416033, 0.80409918,
       0.87769848, 0.21498027, 0.55528632, 0.39252846])

In [15]:
my_list1 = [1,2]

In [16]:
my_list2 = [2,3]

In [17]:
my_list1 + my_list2

[1, 2, 2, 3]

In [18]:
my_numpy_array1 = np.array(my_list1)

In [19]:
my_numpy_array2 =np.array(my_list2)

In [20]:
my_numpy_array1 + my_numpy_array2

array([3, 5])

In [21]:
my_numpy_array1 - my_numpy_array2

array([-1, -1])

In [22]:
my_numpy_array1 * my_numpy_array2

array([2, 6])

In [23]:
my_numpy_array1 / my_numpy_array2

array([0.5       , 0.66666667])

In [24]:
my_numpy_array1 * 5

array([ 5, 10])

In [25]:
other_array = np.array([10,20,30,40,50])

In [26]:
other_array.sum()

np.int64(150)

In [27]:
#indexing & arange

In [28]:
list(range(0,15))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [29]:
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
type(np.arange(0,15))

numpy.ndarray

In [31]:
type(list(range(0,15)))

list

In [33]:
np.arange(0,20,5)

array([ 0,  5, 10, 15])

In [34]:
np_array = np.arange(0,15,3)

In [35]:
np_array

array([ 0,  3,  6,  9, 12])

In [36]:
np_array[-1]

np.int64(12)

In [37]:
np_array1 = np.arange(0,15)

In [38]:
np_array1[1:4:]

array([1, 2, 3])

In [39]:
np_array1[1:9:2]

array([1, 3, 5, 7])

In [40]:
np_array1[::-1]

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [44]:
np.random.randn(2,2) #we will see matrices in details

array([[ 0.70328285, -0.1828124 ],
       [-0.61534657, -0.88465483]])

In [45]:
np.random.randint(1,300,5)

array([299, 199, 286, 224,  25], dtype=int32)