In [1]:
import numpy as np

In [2]:
my_matrix = [[5,10],[15,20]]

In [4]:
my_matrix[0]

[5, 10]

In [5]:
my_matrix[1]

[15, 20]

In [6]:
#my_matrix.sum()

In [7]:
type(my_matrix)

list

In [8]:
numpy_matrix = np.array([[5,10],[15,20]])

In [9]:
type(numpy_matrix)

numpy.ndarray

In [10]:
numpy_matrix.sum()

np.int64(50)

In [11]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.random.random((5,3))

array([[0.08963873, 0.72212293, 0.9723964 ],
       [0.29225425, 0.87402259, 0.68279515],
       [0.3324953 , 0.99126212, 0.14709628],
       [0.16819789, 0.69574278, 0.02433513],
       [0.30609589, 0.16430622, 0.53032882]])

In [20]:
np.random.randint(1,300,5)

array([111, 272, 243, 109, 270], dtype=int32)

In [21]:
first_array = np.array([[15,25],[10,20]])

In [22]:
second_array = np.array([[1,2],[10,20]])

In [23]:
first_array + second_array

array([[16, 27],
       [20, 40]])

In [24]:
first_array

array([[15, 25],
       [10, 20]])

In [25]:
first_array/ 4 

array([[3.75, 6.25],
       [2.5 , 5.  ]])

In [26]:
first_array.shape

(2, 2)

In [27]:
third_array = first_array * second_array

In [28]:
third_array.shape

(2, 2)

In [29]:
third_array

array([[ 15,  50],
       [100, 400]])