In [3]:
import numpy as np

In [5]:
new_array = np.random.randint(1,100,20)

In [6]:
new_array

array([69, 52, 44, 41, 93, 31, 26, 77, 75, 99, 24, 56, 70, 48, 78, 13, 80,
       15, 23, 95], dtype=int32)

In [7]:
new_array > 25

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True, False,  True, False,
       False,  True])

In [8]:
new_array[new_array > 25]

array([69, 52, 44, 41, 93, 31, 26, 77, 75, 99, 56, 70, 48, 78, 80, 95],
      dtype=int32)

In [9]:
#transpose & reshape

In [10]:
matrix_array = np.array([[10,20],[20,30],[30,40]])

In [11]:
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [12]:
matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [13]:
matrix_array.T

array([[10, 20, 30],
       [20, 30, 40]])

In [14]:
random_array = np.random.random((6,1))

In [15]:
random_array

array([[0.41865829],
       [0.28412111],
       [0.48483721],
       [0.1641268 ],
       [0.44379223],
       [0.10346421]])

In [16]:
random_array.reshape(2,3)

array([[0.41865829, 0.28412111, 0.48483721],
       [0.1641268 , 0.44379223, 0.10346421]])

In [17]:
random_array.reshape(3,2)

array([[0.41865829, 0.28412111],
       [0.48483721, 0.1641268 ],
       [0.44379223, 0.10346421]])

In [18]:
#real life cases

In [19]:
data = np.array([10,12,13,15,18,25,100,105])

In [20]:
mean = np.mean(data)

In [21]:
mean

np.float64(37.25)

In [22]:
std= np.std(data)

In [23]:
std

np.float64(37.9333296719389)

In [24]:
z_scores = (data - mean) /std

In [25]:
z_scores

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [26]:
np.abs(z_scores) >1

array([False, False, False, False, False, False,  True,  True])

In [27]:
outliers = data[np.abs(z_scores) >1]

In [28]:
outliers

array([100, 105])

In [29]:
# math equatins

In [30]:
# Solve 2x + 3y=8 and 5x +7y = 19

In [31]:
# Coefficients matrix 
A= np.array([[2,3],[5,7]])

In [32]:
#Constants matrix
B = np.array([8,19])

In [33]:
#Solve for x and y
solution = np.linalg.solve(A,B)

In [34]:
solution

array([1., 2.])

In [35]:
# data analysis

In [36]:
# Stock prices over 5 days

In [37]:
prices =np.array([100,102,105,107,110])

In [38]:
np.diff(prices)

array([2, 3, 2, 3])

In [39]:
len(prices)

5

In [41]:
prices[:len(prices)-1:]

array([100, 102, 105, 107])

In [42]:
prices[:-1:]

array([100, 102, 105, 107])

In [43]:
np.diff(prices)/prices[:-1]

array([0.02      , 0.02941176, 0.01904762, 0.02803738])

In [44]:
returns = np.diff(prices)/prices[:-1] * 100

In [45]:
returns

array([2.        , 2.94117647, 1.9047619 , 2.80373832])